<?xml version="1.0"?>
<package format="3">
  <name>nomoto_plugin</name>
  <version>0.0.0</version>
  <description>Nomoto dynamics Gazebo plugin for ASV</description>
  <maintainer email="user@todo.todo">user</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>gz-sim7</depend>
  <depend>gz-plugin2</depend>
  <depend>gz-math7</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
